
import Image from 'next/image'
import type { Metadata } from "next";
import styles from "@/styles/pages/landing.module.scss";
import Link from 'next/link';
import List from "@/components/board/list";
import CountUpAnimation from '@/components/d3/CountUpAnimation';
import LineChart from '@/components/d3/LineChart';
import Chart from '@/components/d3/BarChart';

export const metadata: Metadata = {
	title: 'aaa',
	description: 'Generated by create next app',
};

export default function landingLayout({ children }) {
    return <>{children}</>
  }
  