import Image from 'next/image'
// import { LineChart } from '@/components/charts/LineChart';
import type { Metadata } from "next";
export const metadata: Metadata = {
	title: 'Overview',
	description: 'Generated by create next app',
};


export default function Overview() {
  return (
    <div className="App">
      
      Overview
    </div>
  );
 }