// 'use client';
import Image from 'next/image'
import type { Metadata } from "next";
import Sidebar from "@/components/layout/sidebar";
import styles from "@/styles/pages/landing.module.scss";
import Link from 'next/link';
import List from "@/components/board/list";
export const metadata: Metadata = {
	title: 'ARGOS - LANDING',
	description: 'Generated by create next app',
};


export default function Landing() {
  return (
    <main className={`${styles.landing} flex justify-start h-screen`}>
    <Sidebar />
    <div className="bg-white w-100 flex items-center justify-center flex-wrap">
        <List type="announce" />
        <List type="support" />
    </div>
    </main>
  )
}